### ISSUE TITLE
Pass the host to the 'done' callback, and main callback. 

### ISSUE THREAD

**Issue by shellscape** [tpresley/node-remote-exec#1]
I'd file a pull request but it's a 2 second change. It'd be great for reporting and/or parsing output to have the 'host' variable passed as the first parameter of the main callbacks (and to make it easy, the 'done' callbacks).

**Comment by tpresley** [comment]
The async library doesn't allow you to pass arguments into the "done" callback, only errors.  So I added an afterEach callback to options that gets host, commands, params, and err arguments.

The main callback isn't in the context of a host, so I can't pass that in, but I could maybe pass an array of hosts that successfully completed.  Is that what you're asking for?

**Comment by shellscape** [comment]
Yeah the idea there is just to know which hosts finished in order.
